### ISSUE TITLE
Missing Scraping data when a User is submitted

### ISSUE THREAD

**Issue by meetg0d** [meetg0d/RSCS#1]
When a user is submitting a twitter account, the backend needs to trigger a data scrape using scweet (twitter scraping bot). 

We are looking for the following data:

- Username
- Display Name
- Followers
- Profile picture link

Once that's done we need the frontend table to fetch the data and create a new user that can be up and downvoted

**Comment by MidpriceDog** [comment]
Hey @meetg0d should I mark this as closed? Give me any details if there needs to be further optimizations made. Seemed like had it covered from your messages in Discord. Feel free to assign me to a new issue as well.
